sudo: required
language: ruby
cache:
  directories:
    - bash
before_install: gem update --system --no-doc # https://github.com/sickill/rainbow/issues/49
before_script:
  - whereis bash
  - bash --version
  - ./spec/install_bash.sh
  - bash --version
after_script:
  - test -z "$MUTANT" || bundle exec mutant --include lib --require bashcov --use rspec 'Bashcov*'
os:
  - linux
  - osx
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - ruby-head
  - rbx-2
env:
  matrix:
    - INSTALL_BASH_VERSION=5.0
    - INSTALL_BASH_VERSION=4.4
    - INSTALL_BASH_VERSION=4.3
    - INSTALL_BASH_VERSION=4.2
    - INSTALL_BASH_VERSION=4.1
    - INSTALL_BASH_VERSION=4.0
    - INSTALL_BASH_VERSION=3.2
    - INSTALL_BASH_VERSION=3.1
    - INSTALL_BASH_VERSION=3.0
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: rbx-2
    - env: INSTALL_BASH_VERSION= MUTANT=1
    - env: INSTALL_BASH_VERSION=4.1
    - env: INSTALL_BASH_VERSION=4.0
